# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
	
	Secret.create(image: 'http://res.cloudinary.com/lawless/image/upload/v1499071948/amegan/circulo1_investment.png', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat aut soluta, veritatis minima mollitia officia officiis alias autem possimus, dolorum tenetur laboriosam quod dolorem et, nesciunt sint at similique quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, error obcaecati neque commodi. Tenetur, quod possimus libero aliquid obcaecati odit. In placeat neque illo sed quam qui sapiente cupiditate nam?')
	Secret.create(image: 'http://res.cloudinary.com/lawless/image/upload/v1499071948/amegan/circulo2_investment.png', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quidem architecto molestias amet corporis veniam delectus, non dolore reprehenderit cupiditate mollitia ullam provident nostrum tempora facilis id sequi, quam saepe! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto corporis magni, est enim facilis! Libero possimus sint soluta vitae hic fugit eaque eum impedit. Rerum culpa quam inventore aliquid sequi.')
	Secret.create(image: 'http://res.cloudinary.com/lawless/image/upload/v1499071948/amegan/circulo3_investment.png', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos repudiandae quidem illum est, adipisci enim exercitationem, ab, harum tempore rem impedit non nobis eveniet voluptatem vel tempora consectetur repellat nulla. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam delectus similique consectetur laboriosam magni, suscipit qui maxime excepturi recusandae natus animi, fuga. Sit autem illo quibusdam. Repudiandae, ipsum, placeat. Pariatur?')
	Secret.create(image: 'http://res.cloudinary.com/lawless/image/upload/v1499071948/amegan/circulo4_investment.png', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi facere deserunt minima temporibus voluptatibus, cumque quia tenetur consectetur. Culpa architecto asperiores aperiam explicabo itaque est recusandae rerum consectetur, excepturi. Libero! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque voluptatibus voluptates, cum, neque esse non ipsa magni adipisci distinctio quae, similique. Vel, placeat unde iusto, saepe earum accusamus tempora itaque.')